# Generated by Django 4.0.4 on 2022-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateMyProfRatings',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('no_of_ratings', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rate_my_prof_ratings',
                'managed': False,
            },
        ),
    ]
