# Generated by Django 4.0.4 on 2022-04-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professor',
            table='rate-my-prof-ratings',
        ),
    ]
